#!/bin/sh

set -eu

usage() {
  cat <<'EOF'
Usage: install_rk3506_release_on_target.sh [options]

Run this script on RK3506. It downloads a prebuilt gateway release tarball,
verifies it with SHA256, installs Neuron and NanoMQ, then starts services.

Options:
  --url <url>             Release tar.gz URL. Required unless --repo and --version are set
  --sha256-url <url>      SHA256 file URL. Default: <url>.sha256
  --repo <url>            GitHub repo URL, for example https://github.com/user/repo
  --version <tag>         Release tag, for example v1.0.0
  --asset <name>          Release asset name. Default: industrial-iot-rk3506-<version>.tar.gz
  --neuron-dir <path>     Install directory. Default: /opt/neuron
  --nanomq-bin <path>     NanoMQ install path. Default: /usr/local/bin/nanomq
  --nanomq-conf <path>    NanoMQ config install path. Default: /etc/nanomq/nanomq.conf
  --no-verify             Skip SHA256 verification
  --skip-start            Install only, do not start services
  -h, --help              Show this help

Examples:
  sh install_rk3506_release_on_target.sh \
    --url https://github.com/user/repo/releases/download/v1.0.0/industrial-iot-rk3506-v1.0.0.tar.gz

  sh install_rk3506_release_on_target.sh \
    --repo https://github.com/user/repo \
    --version v1.0.0
EOF
}

die() {
  echo "error: $*" >&2
  exit 1
}

warn() {
  echo "warning: $*" >&2
}

have_cmd() {
  command -v "$1" >/dev/null 2>&1
}

download() {
  url="$1"
  out="$2"

  if have_cmd curl; then
    curl -fL "$url" -o "$out"
  elif have_cmd wget; then
    wget -O "$out" "$url"
  else
    die "need curl or wget"
  fi
}

verify_sha256() {
  archive="$1"
  checksum_file="$2"

  have_cmd sha256sum || die "need sha256sum, or pass --no-verify"

  # The checksum file generated by make_rk3506_release_bundle.sh uses the
  # standard format: "<sha256>  <filename>". Only the first field matters here.
  set -- $(cat "$checksum_file")
  expected="$1"
  set -- $(sha256sum "$archive")
  actual="$1"

  [ "$actual" = "$expected" ] || die "SHA256 mismatch: expected $expected, got $actual"
}

repo=""
version=""
asset=""
url=""
sha256_url=""
neuron_dir="/opt/neuron"
nanomq_bin="/usr/local/bin/nanomq"
nanomq_conf="/etc/nanomq/nanomq.conf"
verify=1
skip_start=0

while [ "$#" -gt 0 ]; do
  case "$1" in
    --url)
      [ "$#" -ge 2 ] || die "missing value for --url"
      url="$2"
      shift 2
      ;;
    --sha256-url)
      [ "$#" -ge 2 ] || die "missing value for --sha256-url"
      sha256_url="$2"
      shift 2
      ;;
    --repo)
      [ "$#" -ge 2 ] || die "missing value for --repo"
      repo="$2"
      shift 2
      ;;
    --version)
      [ "$#" -ge 2 ] || die "missing value for --version"
      version="$2"
      shift 2
      ;;
    --asset)
      [ "$#" -ge 2 ] || die "missing value for --asset"
      asset="$2"
      shift 2
      ;;
    --neuron-dir)
      [ "$#" -ge 2 ] || die "missing value for --neuron-dir"
      neuron_dir="$2"
      shift 2
      ;;
    --nanomq-bin)
      [ "$#" -ge 2 ] || die "missing value for --nanomq-bin"
      nanomq_bin="$2"
      shift 2
      ;;
    --nanomq-conf)
      [ "$#" -ge 2 ] || die "missing value for --nanomq-conf"
      nanomq_conf="$2"
      shift 2
      ;;
    --no-verify)
      verify=0
      shift
      ;;
    --skip-start)
      skip_start=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      die "unknown option: $1"
      ;;
  esac
done

[ "$(id -u)" = "0" ] || die "please run as root"
have_cmd tar || die "need tar"
have_cmd uname || die "need uname"

case "$(uname -m)" in
  armv7l|armv7*|arm*)
    ;;
  *)
    die "unsupported architecture: $(uname -m). This package is for RK3506 ARMHF"
    ;;
esac

if [ -z "$url" ]; then
  [ -n "$repo" ] || die "provide --url, or provide --repo and --version"
  [ -n "$version" ] || die "provide --version with --repo"
  if [ -z "$asset" ]; then
    asset="industrial-iot-rk3506-$version.tar.gz"
  fi
  url="$repo/releases/download/$version/$asset"
fi

if [ -z "$sha256_url" ]; then
  sha256_url="$url.sha256"
fi

tmp_dir="${TMPDIR:-/tmp}/neuron-rk3506-install.$$"
archive="$tmp_dir/release.tar.gz"
checksum_file="$tmp_dir/release.tar.gz.sha256"
new_dir="$neuron_dir.new.$$"
backup_dir="$neuron_dir.backup.$(date +%Y%m%d%H%M%S 2>/dev/null || echo $$)"

cleanup() {
  rm -rf "$tmp_dir" "$new_dir"
}
trap cleanup EXIT INT TERM

mkdir -p "$tmp_dir/extract"

echo "==> Downloading release:"
echo "    $url"
download "$url" "$archive"

if [ "$verify" = "1" ]; then
  echo "==> Downloading SHA256:"
  echo "    $sha256_url"
  download "$sha256_url" "$checksum_file"
  echo "==> Verifying SHA256"
  verify_sha256 "$archive" "$checksum_file"
else
  warn "SHA256 verification skipped"
fi

echo "==> Extracting release"
tar -xzf "$archive" -C "$tmp_dir/extract"

bundle_neuron_dir="$tmp_dir/extract/neuron"
[ -f "$bundle_neuron_dir/neuron" ] || die "invalid release: missing neuron executable"
[ -d "$bundle_neuron_dir/lib" ] || die "invalid release: missing lib directory"
[ -d "$bundle_neuron_dir/plugins" ] || die "invalid release: missing plugins directory"
[ -d "$bundle_neuron_dir/config" ] || die "invalid release: missing config directory"

bundle_nanomq_bin="$tmp_dir/extract/nanomq/bin/nanomq"
bundle_nanomq_etc="$tmp_dir/extract/nanomq/etc"
[ -f "$bundle_nanomq_bin" ] || die "invalid release: missing nanomq binary"
[ -d "$bundle_nanomq_etc" ] || die "invalid release: missing nanomq config directory"

echo "==> Stopping services"
if [ -x "$nanomq_bin" ]; then
  "$nanomq_bin" stop >/tmp/nanomq-stop.log 2>&1 || true
else
  warn "$nanomq_bin not found before install"
fi
pkill neuron >/dev/null 2>&1 || true
sleep 1

echo "==> Preparing install directory"
rm -rf "$new_dir"
mkdir -p "$new_dir"
cp -a "$bundle_neuron_dir"/. "$new_dir"/
chmod +x "$new_dir/neuron"

echo "==> Installing Neuron to $neuron_dir"
if [ -e "$neuron_dir" ]; then
  rm -rf "$backup_dir"
  mv "$neuron_dir" "$backup_dir"
  echo "    backup: $backup_dir"
fi
mv "$new_dir" "$neuron_dir"

# Neuron reads some migration schema paths after normalizing
# /opt/neuron/config to opt/neuron/config. When the daemon is started from
# /opt/neuron, keep that normalized relative path resolvable.
mkdir -p "$neuron_dir/opt/neuron"
rm -rf "$neuron_dir/opt/neuron/config"
ln -s "$neuron_dir/config" "$neuron_dir/opt/neuron/config"

echo "==> Installing NanoMQ to $nanomq_bin"
mkdir -p "$(dirname "$nanomq_bin")" "$(dirname "$nanomq_conf")"
cp -a "$bundle_nanomq_bin" "$nanomq_bin"
chmod +x "$nanomq_bin"
cp -a "$bundle_nanomq_etc"/. "$(dirname "$nanomq_conf")"/
if [ ! -f "$nanomq_conf" ]; then
  if [ -f "$(dirname "$nanomq_conf")/nanomq.conf" ]; then
    :
  else
    die "NanoMQ config not installed: $nanomq_conf"
  fi
fi

if [ "$skip_start" = "1" ]; then
  echo "==> Install complete. Service start skipped."
  exit 0
fi

echo "==> Starting NanoMQ"
if [ -x "$nanomq_bin" ] && [ -f "$nanomq_conf" ]; then
  nohup "$nanomq_bin" start \
    --conf "$nanomq_conf" \
    --log_level info \
    --log_stdout false \
    >/tmp/nanomq-stdout.log 2>&1 &
elif [ -x "$nanomq_bin" ]; then
  warn "NanoMQ config not found: $nanomq_conf; skip NanoMQ start"
fi

echo "==> Starting Neuron"
cd "$neuron_dir"
LD_LIBRARY_PATH="$neuron_dir/lib" ./neuron \
  --config_dir "$neuron_dir/config" \
  --plugin_dir "$neuron_dir/plugins" \
  -d

sleep 2
ps | grep -E 'neuron|nanomq' | grep -v grep || true
netstat -lntp 2>/dev/null | grep -E ':(7000|1883)' || true

echo "==> Done"
